#!/bin/sh /etc/rc.common

#
# Startup/shutdown script for opennds captive portal
#

START=15
STOP=99

USE_PROCD=1

# Run in PROCD (-f)
OPTIONS="-f"

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/opennds $OPTIONS
	procd_set_param respawn
	procd_close_instance
	/usr/lib/opennds/libopennds.sh users_to_router allow
}

stop_service() {
	# When procd terminates opennds, it does not exit fast enough.
	# Otherwise procd will restart opennds twice. First time starting
	# opennds fails, second time it succeeds.
	sleep 1
	/usr/lib/opennds/libopennds.sh users_to_router cleanup
}
