#!/bin/sh /etc/rc.common

#
# Startup/shutdown script for opennds captive portal
#

START=15
STOP=99

USE_PROCD=1

# Run in PROCD (-f)
OPTIONS="-f"

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/opennds $OPTIONS
	procd_set_param respawn
	procd_set_param term_timeout 60 # wait before sending SIGKILL
	procd_set_param stdout 1
	procd_close_instance
	/usr/lib/opennds/libopennds.sh users_to_router allow
}

stop_service() {
	/usr/lib/opennds/libopennds.sh users_to_router cleanup
}
