name: Test Formalities

on:
  pull_request:

jobs:
  build:
    name: Test Formalities
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Determine branch name
        run: |
          BRANCH="${GITHUB_BASE_REF#refs/heads/}"
          echo "Building for $BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Test for merge commits, S.O.B.
        run: |
          source .github/workflows/ci_helpers.sh

          RET=0
          for commit in $(git rev-list HEAD ^origin/$BRANCH); do
            info "=== Checking commit '$commit'"
            if git show --format='%P' -s $commit | grep -qF ' '; then
              err "Pull request should not include merge commits"
              RET=1
            fi

            body="$(git show -s --format=%b $commit)"
            authoremail="$(git show -s --format='<%aE>' $commit)"
            sob="$(git show -s --format='Signed-off-by: %aN <%aE>' $commit)"
            if echo "$body" | grep -qF "$sob"; then
              success "Signed-off-by matches author"
            else
              err "Signed-off-by is missing or doesn't match author (should be '$sob')"
              RET=1
            fi

          done

          exit $RET
